name: éƒ¨ç½²åˆ°ç§æœ

on: 
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/checkout@v4
        with:
          repository: nichuanfang/blog-docs-next-vercel
          ref: main
          fetch-depth: 0
          persist-credentials: false
          path: blog-docs-next-vercel

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.OS }}-yarn-cache
          restore-keys: |
            ${{ runner.OS }}-yarn-cache

      # å®‰è£…yarn
      - name: Install yarn
        run: |
          npm install -g yarn

      - name: build docs
        run: |
          yarn add -D vuepress
          yarn docs:build

      - name: å‘å¸ƒåˆ°vercelä»“åº“
        uses: Smart-Transportation/push@v1.3
        with:
          directory: ./blog-docs-next-vercel
          github_token: ${{ secrets.GH_TOKEN }}
          branch: 'main'
          author_email: 'f18326186224@gmail.com'
          author_name: 'nichuanfang'
          message: 'ğŸ³ chore: æ›´æ–°vercelä»“åº“'
          repository: nichuanfang/blog-docs-next-vercel
